# Generated by Django 5.2 on 2025-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Token_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Amount', models.IntegerField()),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
